#!/bin/bash -e
# regenerate rails secret key and pgsql password

. /etc/default/inithooks

APPNAME=$(cat /etc/turnkey_version  | perl -pe 's/^turnkey-//; s/-[^-]+(-[^-]+){2}$//')
[ "$APPNAME" == "rails" ] && APPNAME=railsapp ## namespace conflict
WEBROOT=/var/www/$APPNAME

# rails 4.1
CONF=$WEBROOT/config/secrets.yml
[ -e $CONF ] && sed -i "s|secret_key_base:.*|secret_key_base: '$(mcookie)$(mcookie)$(mcookie)$(mcookie)'|" $CONF

# rails 4.0
CONF=$WEBROOT/config/initializers/secret_token.rb
[ -e $CONF ] && sed -i "s|Application.config.secret_key_base\\s*=.*|Application.config.secret_key_base = '$(mcookie)$(mcookie)$(mcookie)$(mcookie)'|" $CONF

# rails 3.2
CONF=$WEBROOT/config/initializers/secret_token.rb
[ -e $CONF ] && sed -i "s|Application.config.secret_token\\s*=.*|Application.config.secret_token = '$(mcookie)$(mcookie)$(mcookie)$(mcookie)'|" $CONF

# rails 2.3
CONF=$WEBROOT/config/initializers/session_store.rb
[ -e $CONF ] && sed -i "s|:secret\\s*=>.*|:secret => \'$(mcookie)$(mcookie)\'|" $CONF

# rails 2.2
CONF=$WEBROOT/config/site.yml
[ -e $CONF ] && sed -i "s|^salt:.*|salt: \"$(mcookie)\"|" $CONF

# regen pgsql password
PASSWORD=$(mcookie)
CONF=$WEBROOT/config/database.yml
sed -i "s|password:.*|password: $PASSWORD|g" $CONF
$INITHOOKS_PATH/bin/pgsqlconf.py --user=$APPNAME --pass="$PASSWORD"

# remove innodb logfiles (workarounds really weird bug)
rm -f /var/lib/mysql/ib_logfile*

# restart passenger
touch $WEBROOT/tmp/restart.txt

