#!/bin/bash -e
# regenerate rails secret key and pgsql password

. /etc/default/inithooks

export RAILS_ENV=production

APPNAME=$(turnkey-version --name)
[[ "$APPNAME" != "rails" ]] || APPNAME=railsapp ## namespace conflict
WEBROOT=/var/www/$APPNAME

CRED_FILE=$WEBROOT/config/credentials.yml.enc
KEY_FILE=$WEBROOT/config/master.key

# regen master key and credentials files
stamp=$(date +%s)
echo "Regenerating rails secrets"
for _file in $CRED_FILE $KEY_FILE; do
    if [[ -f "$_file" ]]; then
        bak="$_file.$stamp.bak"
        echo "WARNING: Backing up existing $_file as $bak." >&2
        mv $_file $bak
   fi
done

cd $WEBROOT
# set editor as echo - hack to regen default files non-interactively
EDITOR=echo rails credentials:edit
chown www-data:www-data $CRED_FILE $KEY_FILE

# regen pgsql password
PASSWORD=$(mcookie)
CONF=$WEBROOT/config/database.yml
sed -i "s|password:.*|password: $PASSWORD|g" $CONF
$INITHOOKS_PATH/bin/pgsqlconf.py --user=$APPNAME --pass="$PASSWORD"

# restart passenger
touch $WEBROOT/tmp/restart.txt
