#!/bin/bash -e
# create apt sources
# environment variables:
#   - required: CODENAME
#   - optional: NONFREE

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

[ -n "$CODENAME" ] || fatal "CODENAME is not set"

SOURCES_LIST=/etc/apt/sources.list.d
PREFS_LIST=/etc/apt/preferences.d
mkdir -p $SOURCES_LIST $PREFS_LIST

cat > $SOURCES_LIST/sources.list <<EOF
deb http://archive.turnkeylinux.org/debian $CODENAME main

deb http://deb.debian.org/debian $CODENAME main
deb http://deb.debian.org/debian $CODENAME contrib
#deb http://deb.debian.org/debian $CODENAME non-free
EOF

cat > $SOURCES_LIST/security.sources.list <<EOF
deb http://archive.turnkeylinux.org/debian $CODENAME-security main

deb http://security.debian.org/ $CODENAME/updates main
deb http://security.debian.org/ $CODENAME/updates contrib
#deb http://security.debian.org/ $CODENAME/updates non-free
EOF

if [ -n "$PHP_VERSION" ]; then
    # install support for https repo
    PKGS="apt-transport-https lsb-release ca-certificates"
    apt update
    DEBIAN_FRONTEND=noninteractive apt install -y $PKGS

    cat > $SOURCES_LIST/php.list <<EOF
# DEB.SURY.ORG repo for php

deb [signed-by=/usr/share/keyrings/php-sury.org.gpg] https://packages.sury.org/php/ stretch main
EOF

    cat > /etc/apt/preferences.d/php-sury.pref <<EOF
Package: *
Pin: origin packages.sury.org
Pin-Priority: 100

Package: php${PHP_VERSION}-*
Pin: origin packages.sury.org
Pin-Priority: 550

Package: php-pear
Pin: origin packages.sury.org
Pin-Priority: 550

Package: libapache2-mod-php${PHP_VERSION}
Pin: origin packages.sury.org
Pin-Priority: 550
EOF
    if [[ "$(awk 'BEGIN{ print 7.0<'${PHP_VERSION}' }')" == '1' ]]; then
        cat >> /etc/apt/preferences.d/php-sury.pref <<EOF

Package: libpcre3
Pin: origin packages.sury.org
Pin-Priority: 550

Package: libzip4
Pin: origin packages.sury.org
Pin-Priority: 550
EOF
    fi

fi

if [ "$NONFREE" ]; then
    sed -i "/non-free/ s|^#||" $SOURCES_LIST/sources.list
    sed -i "/non-free/ s|^#||" $SOURCES_LIST/security.sources.list
fi
