#!/bin/bash -e

# copy in confconsole auto start file
mkdir -p /root/.bashrc.d/
cp /usr/share/confconsole/autostart/confconsole-auto \
    /root/.bashrc.d/confconsole-auto
# should already be executable, but just in case
chmod +x /root/.bashrc.d/confconsole-auto

# autostart "once"
CONF=/etc/confconsole/confconsole.conf
sed -i "s|^#autostart|autostart|g" $CONF
sed -i "s|^autostart.*|autostart once|g" $CONF
