#!/bin/bash -e

# Note that a Confconsole plugin that allows the user to select between these
# profiles is included as overlays/turnkey.d/cronapt-confconsole

[ -e /etc/cron-apt ] || exit 0

cd /etc/cron-apt
mkdir -p action-available.d

cat >> config << EOF
MAILON="never"
SYSLOGON="output"
EOF

echo -n > action.d/3-download

cat > TurnKey_Linux_5-install.README << EOF
# The files in actiona-available.d named '5-install.XXX' relate to the
# '5-install' cronapt script located in /etc/cron-apt/actions.d/
#
# Which particular action to be applied is determined by which file the
# symlink /etc/cron-apt/config.d/5-install points to.
#
# To double check this; use this::
#
#       ls -l /etc/cron-apt/action.d/5-install
#
# E.g. here is the expected output under default condition (only important
# part shown)::
#
#       /etc/cron-apt/action.d/5-install -> ../action-available.d/5-install.default
#
# 5-install.default aka 'default'
# -------------------------------
#
# This is the historic and default TurnKey cron-apt behaviour. Only packages
# from the security.sources.list repositories will be installed. Any conflicts
# or missing dependencies will not be installed and will cause package removal.
# This package removal may cause one or more services to fail.
#
# 5-install.alt aka 'alternate'
# -----------------------------
#
# This is a new option which is similar to the default. However, it will not
# allow removal of packages. This will maximise uptime of all services, but
# conversely, may also allow services with unpatched security vulnerabilities
# to continue running.
EOF

cat > action-available.d/5-install.default << EOF
autoclean -y
dist-upgrade -y \
    -o APT::Get::Show-Upgraded=true \
    -o Dir::Etc::sourcelist=/etc/apt/sources.list.d/security.sources.list \
    -o Dir::Etc::sourceparts=nonexistent \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold
EOF

cat > action-available.d/5-install.alt << EOF
autoclean -y
upgrade -y \
    -o APT::Get::Upgrade-Allow-New=true \
    -o APT::Get::Show-Upgraded=true \
    -o Dir::Etc::sourcelist=/etc/apt/sources.list.d/security.sources.list \
    -o Dir::Etc::sourceparts=nonexistent \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold
EOF

# Enable original config as default
ln -sf ../action-available.d/5-install.default action.d/5-install
