#!/bin/bash -e

if ! grep -s '^noarp' /etc/dhcpcd.conf; then
    cat >> /etc/dhcpcd.conf <<EOF

# disable ARP probe - consistent behavior with udhcpd & works around slow
# network start on boot for some buggy DHCP implementations
noarp
EOF
fi
