#!/bin/bash -e

# explictly allow ipv6 - see Debian bug #1024305:
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1024305

CONF=/etc/fail2ban/fail2ban.conf
if ! grep -q '^allowipv6' $CONF; then
    sed -i '\|^\[Definition\]|a \\nallowipv6 = auto' $CONF
fi

cat > /etc/cron.weekly/fail2ban <<EOF
#!/bin/sh
#
# If fail2ban is using sqlite (not the default in TurnKey) periodically vacuum
# database to prevent it growing endlessly - see Debian Bug #1010011
# - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010011

sqlite="/usr/bin/sqlite3"
database="/var/lib/fail2ban/fail2ban.sqlite3"

[ -x \$sqlite ] && [ -f \$database ] || exit 0

\$sqlite \$database "VACUUM;"
EOF
chmod +x /etc/cron.weekly/fail2ban

# On firstboot (especially live) a race condition can occur where the auth.log
# does not exist (yet) when fail2ban tries to start; which causes it to fail.
# So make sure it exists:
touch /var/log/auth.log
# set permissions as per default
chown root:adm /var/log/auth.log
chmod 640 /var/log/auth.log
