#!/bin/bash -e

# make fail2ban default to reading journal - see #1844 (Debian #1037437)
sed -i "\|^backend = auto|s|auto|systemd|" /etc/fail2ban/jail.conf

# On firstboot (especially live) a race condition can occur where the auth.log
# does not exist (yet) when fail2ban tries to start; which causes it to fail.
# So make sure it exists:
touch /var/log/auth.log
# set permissions as per default
chown root:adm /var/log/auth.log
chmod 640 /var/log/auth.log
