#!/bin/bash -e

# use traditional network interface names; aka disable "Predictable Network
# Interface Names" - see 
# https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

sed -i '/GRUB_CMDLINE_LINUX=/ s|="|="net.ifnames=0 |' /etc/default/grub
