#!/bin/sh -e

if [ ! $HOSTNAME ]; then
    echo "'$(basename $0)' error: hostname not defined"
    return 1
fi

echo "$HOSTNAME" > /etc/hostname
cat > /etc/hosts <<EOF
127.0.0.1 localhost
127.0.1.1 $HOSTNAME

#Required for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
EOF

interfaces=/etc/network/interfaces
if [ -f "$interfaces" ]; then
    sed -i "s|_UNCONFIGURED_|$HOSTNAME|" $interfaces
else
    echo "Error $interfaces file not found - can't update hostname"
    return 1
fi
