#!/bin/sh -e

cat >> /etc/default/locale << EOF
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_ALL=C
LC_CTYPE=C
EOF

cat > /etc/locale.nopurge << EOF
## Configuration file for localepurge(8)

# Remove localized man pages
MANDELETE

# Delete new locales which appear on the system without bothering you
DONTBOTHERNEWLOCALE

# Display freed disk space when purging superfluous data
#SHOWFREEDSPACE

# Use faster (but less accurate) free space calculation
#QUICKNDIRTYCALC

# Display verbose output
#VERBOSE

# Keep these locales after package installations via apt-get(8)
en
en_US
en_US.UTF-8
EOF

# hack: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=684134
sed -i '/en_US.UTF-8 UTF-8/ s/# //' /etc/locale.gen

debconf-set-selections <<END
locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8
locales locales/default_environment_locale select en_US.UTF-8
END
DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales

localepurge

