#!/bin/sh -e
# uncomment multiverse

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

if [ "$MULTIVERSE" ]; then
    [ -n "$CODENAME" ] || fatal "CODENAME is not set"

    APT_SOURCES=/etc/apt/sources.list.d
    sed -i "/$CODENAME multiverse/ s/# //" $APT_SOURCES/sources.list
    sed -i "/$CODENAME-updates multiverse/ s/# //" $APT_SOURCES/sources.list
    sed -i "/$CODENAME-security multiverse/ s/# //" $APT_SOURCES/security.sources.list
fi

