#!/bin/sh -e
# uncomment non-free

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

if [ "$NONFREE" ]; then
    [ -n "$CODENAME" ] || fatal "CODENAME is not set"

    APT_SOURCES=/etc/apt/sources.list.d
    sed -i "/$CODENAME non-free/ s/# //" $APT_SOURCES/sources.list
    sed -i "/$CODENAME-updates non-free/ s/# //" $APT_SOURCES/sources.list
    sed -i "/$CODENAME-security non-free/ s/# //" $APT_SOURCES/security.sources.list
fi

