#!/bin/bash -e

fatal() { "'$(basename "$0")' Error: $*" >&2; exit 1; }

if [[ -z "$HOSTNAME" ]]; then
    fatal "Hostname not defined"
fi

if grep -q ':25' <(ss -tlnp); then
    fatal "Port 25 is already in use - must be available to set up postfix"
fi

postconf -e inet_interfaces=localhost
postconf -e myhostname="$HOSTNAME"

# harden postfix
# - we don't want '$myhostname' to be expanded
# shellcheck disable=SC2016
postconf -e smtpd_banner='$myhostname ESMTP'

# force TLS connections only - might break sending of mail so leaving disabled
#postconf -e smtpd_tls_auth_only=yes

# by default leave the snakeoil cert/key in place
#postconf -e smtpd_tls_cert_file=/etc/ssl/private/cert.pem
#postconf -e smtpd_tls_key_file=/etc/ssl/private/cert.key

postconf -e smtpd_tls_auth_only=yes
postconf -e tls_preempt_cipherlist=no
postconf -e smtpd_tls_mandatory_protocols='>=TLSv1.2'
postconf -e smtpd_tls_protocols='>=TLSv1.2'
postconf -e smtp_tls_mandatory_ciphers=medium
postconf -e smtpd_tls_mandatory_ciphers=medium

# ciphers set by common/conf/turnkey.d/zz-ssl-ciphers
postconf -e tls_medium_cipherlist="ZZ_SSL_CIPHERS"

postmulti -x postfix start
systemctl enable postfix@-.service
postmulti -x postfix stop
