#!/bin/bash -e

# harden ssh client directories
mkdir -m 0700 /etc/skel/.ssh
cp -dRn /etc/skel/.ssh /root

cp /etc/skel/.bashrc /root
[ -d /etc/skel/.bashrc.d ] && cp -dRn /etc/skel/.bashrc.d /root

cp /etc/skel/.profile /root
[ -d /etc/skel/.profile.d ] && cp -dRn /etc/skel/.profile.d /root

exit 0
