#!/bin/bash -e

CERT_DIR=/etc/ssl/certs
CERT_GRP=certssl

# create symlink for shellinabox (why can't we just specify the certificate?)
ln -s $CERT_DIR/cert.pem /var/lib/shellinabox/certificate.pem

# set permissions for certssl group
addgroup $CERT_GRP
chgrp $CERT_GRP $CERT_DIR/cert.pem
chmod 640 $CERT_DIR/cert.pem

# create default configuration
cat >/etc/default/shellinabox<<EOF
SHELLINABOX_DAEMON_START=1
SHELLINABOX_PORT=12320
SHELLINABOX_GROUP=$CERT_GRP
SHELLINABOX_ARGS=--no-beep
EOF

# update securetty (for root login)
echo >> /etc/securetty
echo "# shellinabox" >> /etc/securetty
declare -i COUNT=0
while [ $COUNT -le 40 ]; do
    echo "pts/$COUNT" >> /etc/securetty
    ((COUNT=$COUNT+1))
done

