#!/bin/bash -e

# create default configuration
cat >/etc/default/shellinabox<<EOF
SHELLINABOX_DAEMON_START=1
SHELLINABOX_PORT=12319
SHELLINABOX_ARGS="--no-beep --disable-ssl --localhost-only"
EOF

# enable stunnel to automatically start services
sed -i "s|ENABLED=0|ENABLED=1|" /etc/default/stunnel4

# configure stunnel to provide ssl support
cat >>/etc/stunnel/stunnel.conf<<EOF
[shellinabox]
accept  = 12320
connect = 127.0.0.1:12319

EOF

# update securetty (for root login)
echo >> /etc/securetty
echo "# shellinabox" >> /etc/securetty
declare -i COUNT=0
while [ $COUNT -le 40 ]; do
    echo "pts/$COUNT" >> /etc/securetty
    ((COUNT=$COUNT+1))
done

