#!/bin/bash -e

# permit root ssh login with password
sed -i "/^PermitRootLogin/ s/without-password/yes/" /etc/ssh/sshd_config

# disable sshd dns checks (if resolution fails will prevent logins)
echo "UseDNS no" >> /etc/ssh/sshd_config

# configure root login banner directive (enabled by inithooks#sudoadmin)
cat >> /etc/ssh/sshd_config <<EOF

Match user root
Banner /root/.ssh/banner
Match user *
EOF

# harden ssh daemon
sed -i '{
  /^UsePrivilegeSeparation/ s/yes/sandbox/
  /^X11Forwarding/ s/yes/no/
  /^TCPKeepAlive/ s/yes/no/
  /^UsePrivilegeSeparation/ a\
\
# SSH hardening recommended by lynis\
AllowTcpForwarding no\
ClientAliveCountMax 2\
MaxAuthTries 2\
MaxSessions 2
}' /etc/ssh/sshd_config

