#!/bin/sh -e
# configure the system for our certificate

set ${CERTFILE:="/etc/ssl/private/cert.pem"}
set ${CRTFILE:="/usr/local/share/ca-certificates/cert.crt"}
set ${KEYFILE:="/etc/ssl/private/cert.key"}
set ${DHPARAMS:="/etc/ssl/private/dhparams.pem"}

# set certificate permissions
if [ -d "/etc/ssl" ]; then
    chmod 400 $KEYFILE
    chmod 400 $CERTFILE
    chmod 400 $DHPARAMS
    chmod 644 $CRTFILE
fi
