#!/bin/sh -e
# configure the system for our certificate

escape_path() {
    echo $1 | sed "s/\//\\\\\//g"
}

CERTFILE=/etc/ssl/certs/cert.pem

# set certificate permissions
if grep -q ^certssl: /etc/group; then
    chgrp certssl $CERTFILE
    chmod 640 $CERTFILE
else
    chmod 600 $CERTFILE
fi
