#!/bin/sh -e
if [ ! -L /etc/webmin/system-status/history ]; then
    mkdir -p /etc/webmin/system-status/history
    mv /etc/webmin/system-status/history /var/webmin/
fi
ln -sf /var/webmin/history /etc/webmin/system-status/history
