#!/bin/sh -e

set ${WEBMIN_PORT:=12321}

# configure stunnel to provide ssl support
cat >>/etc/stunnel/stunnel.conf<<EOF
[webmin]
accept  = $WEBMIN_PORT
connect = 127.0.0.1:10000
TIMEOUTclose = 0
EOF

CONF=/etc/webmin/miniserv.conf

sed -i '/^ssl=/ s|=.*|=|' $CONF
sed -i '/^ipv6=/ s|=.*|=0|' $CONF

cat >> $CONF <<EOF
inetd_ssl=1
bind=127.0.0.1
sockets=
no_resolv_myname=0
EOF
