#!/bin/sh -e

# Stunnel TLS/SSL support for Webmin is now configured via a stunnel.conf file
# - see webmin and/or stunnel common overlays for details; sevice is enabled
# here (note systemctl exits with non-zero exit code, but it does work):
systemctl enable stunnel4@webmin.service || true

WEBMIN_PORT=${WEBMIN_PORT:=12321}

sed -i "/^accept/ s|=.*|= :::$WEBMIN_PORT|" /etc/stunnel/webmin.conf

CONF=/etc/webmin/miniserv.conf

sed -i '/^ssl=/ s|=.*|=|' $CONF
sed -i '/^ipv6=/ s|=.*|=0|' $CONF

cat >> $CONF <<EOF
inetd_ssl=1
bind=127.0.0.1
sockets=
no_resolv_myname=0
EOF
