#!/bin/sh -e

CONF=/etc/webmin/miniserv.conf

update_or_add() {
    key=$1
    value=$2
    if grep -q "$key" $CONF; then
        sed -i "s|$key=.*|$key=$value|" $CONF
    else
        echo "$key=$value" >> $CONF
    fi
}

update_or_add port 12321
update_or_add listen 12321
update_or_add keyfile /etc/ssl/private/cert.pem
update_or_add certfile
update_or_add cipher_list_def 0
update_or_add error_handler_401 401.cgi
update_or_add error_handler_404 404.cgi
update_or_add error_handler_403 403.cgi
update_or_add nolog '\/stats\.cgi\?xhr\-stats\=general'
update_or_add no_tls1 1
update_or_add no_tls1_1 1
update_or_add no_tls1_2
update_or_add extracas
update_or_add ssl_hsts 0
