#!/bin/sh -e

# set up convenience links to Webmin log files

WEBMIN_VAR=/var/webmin
WEBMIN_LOG=/var/log/webmin

mkdir -p $WEBMIN_LOG

files="miniserv.log miniserv.error webmin.log"
for f in $files; do
    ln -s $WEBMIN_VAR/$f $WEBMIN_LOG/$f
done
