#!/bin/sh -e

set ${WEBMIN_FW_TCP_INCOMING:=22 80 443 12320 12321}

CONF=/etc/iptables.up.rules

cat > $CONF <<EOF
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
$WEBMIN_FW_NAT_EXTRA
COMMIT
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
$WEBMIN_FW_MANGLE_EXTRA
COMMIT
*filter
:FORWARD ACCEPT [0:0]
:INPUT DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type echo-request -j ACCEPT
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
EOF

for port in $WEBMIN_FW_TCP_INCOMING; do
    echo "-A INPUT -p tcp -m tcp --dport $port -j ACCEPT" >> $CONF
done

if [ "$WEBMIN_FW_UDP_INCOMING" ]; then
    for port in $WEBMIN_FW_UDP_INCOMING; do
        echo "-A INPUT -p udp -m udp --dport $port -j ACCEPT" >> $CONF
    done
fi

if [ "$WEBMIN_FW_TCP_INCOMING_REJECT" ]; then
    for port in $WEBMIN_FW_TCP_INCOMING_REJECT; do
        echo "-A INPUT -p tcp -m tcp --dport $port -j REJECT" >> $CONF
    done
fi

echo "COMMIT" >> $CONF

sed -i "/^$/d" $CONF

# As of Buster, Debian uses nftables for firewall; but webmin only supports legacy
# iptables - see https://github.com/webmin/webmin/issues/1097
update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
