#!/bin/bash -e
#
# zz-ssl-ciphers
#
# This script was instigated by John Carver 
# It provides a common set of hardened SSL/TLS ciphers fo all webserver apps
# Base configuration is provided by relevant overlay files

set "${CERTFILE:="/etc/ssl/private/cert.pem"}"
set "${CRTFILE:="/usr/local/share/ca-certificates/cert.crt"}"
set "${KEYFILE:="/etc/ssl/private/cert.key"}"
set "${DHPARAMS:="/etc/ssl/private/dhparams.pem"}"

# "Intermediate" Secure Cipher List recommended by Mozilla:
# https://ssl-config.mozilla.org/

SECURE_CIPHER_LIST="ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305"

# Tomcat 10 & 11 use slightly different cipher list - requires Java 10+
TOMCAT_SECURE_CIPHER_LIST="TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305"

fatal() {
    echo "fatal: $*" 1>&2
    exit 1
}

# Postfix
CONF=/etc/postfix/main.cf
if [[ -f "$CONF" ]]; then
    sed -i "/tls_medium_cipherlist/ s|ZZ_SSL_CIPHERS|$SECURE_CIPHER_LIST|" $CONF
fi

# Nginx
CONF="/etc/nginx/snippets/ssl.conf"
if [[ -f "$CONF" ]]; then
    # SSL enabled by default (see overlay)
    sed -i "s|ssl_ciphers '.*|ssl_ciphers '${SECURE_CIPHER_LIST}';|" $CONF
fi

# Lighttpd
CONF="/etc/lighttpd/ssl-params.conf"
if [[ -f "$CONF" ]]; then
    sed -i "/CipherString/ s|ZZ_SSL_CIPHERS|$SECURE_CIPHER_LIST|" $CONF
    lighty-enable-mod ssl
fi

# Tomcat
# Note uses slightly different cipher list in TKL v19.x
for CONF in /etc/tomcat*/server.xml; do
    if [[ -f "$CONF" ]]; then
        sed -i "s|ciphers=|ciphers=\"${TOMCAT_SECURE_CIPHER_LIST}\"|" "$CONF"
    fi
done

CONF=/etc/webmin/miniserv.conf
echo "ssl_cipher_list=$SECURE_CIPHER_LIST" >> $CONF

# Pure-FTPd
PUREFTPDDIR="/etc/pure-ftpd/conf"
if [ -d "$PUREFTPDDIR" ]; then
    echo 1 > ${PUREFTPDDIR}/TLS
    echo HIGH:\!TLSv1:\!TLSv1.1:\!SSLv2:\!SSLv3:${SECURE_CIPHER_LIST} > ${PUREFTPDDIR}/TLSCipherSuite
fi

echo "$SECURE_CIPHER_LIST" > /tmp/ZZ_SSL_CIPHERS
