ssl_certificate     /etc/ssl/private/cert.pem;
ssl_certificate_key /etc/ssl/private/cert.key;

http2 on;


ssl_protocols TLSv1.2 TLSv1.3;
ssl_ecdh_curve X25519:prime256v1:secp384r1;
# ciphers added by conf/turnkey.d/zz-ssl-ciphers script
ssl_ciphers 'ZZ_SSL_CIPHERS';
ssl_prefer_server_ciphers off;

ssl_dhparam /etc/ssl/private/dhparams.pem;

add_header X-Content-Type-Options nosniff;

# HSTS
add_header Strict-Transport-Security "max-age=63072000" always;
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    return 301 https://$host$request_uri;
}

# see also ssl_session_ticket_key alternative to stateful session cache
ssl_session_timeout 1d;
ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions

# OCSP stapling (disabled by default)
#ssl_stapling on;
#ssl_stapling_verify on;
# verify chain of trust of OCSP response using Root CA and Intermediate certs
#ssl_trusted_certificate /path/to/root_CA_cert_plus_intermediates;

# replace with the IP address of your resolver;
# async 'resolver' is important for proper operation of OCSP stapling
#resolver 127.0.0.1;
# If certificates are marked OCSP Must-Staple, consider managing the
# OCSP stapling cache with an external script, e.g. certbot-ocsp-fetcher

server_tokens off;
