#!/bin/bash -e
# set FQDN - fully qualified domain name

. /etc/default/inithooks

updateconf() {
    if [ -z $1 ]; then
        echo "$1=\"$2\"" >> $INITHOOKS_CONF
    fi
}

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

if [ -z $APP_FQDN ]; then
    # Find the app ip address
    APP_IP=${APP_IP:-$(ip route get "$(ip route show to 0/0 | grep -m1 -oP '(?<=via )\S+')" | grep -oP '(?<=src )\S+')}
    updateconf('APP_IP' "$APP_IP")

    # Find the app fully qualified domain name
    APP_FQDN=${APP_FQDN:-$(getent hosts $APP_IP | awk '{ print $2 }')}
    updateconf('APP_FQDN' "$APP_FQDN")

    # Ask user to verify FQDN
    $INITHOOKS_PATH/bin/ask-fqdn.py --fqdn="$APP_FQDN"
fi

