#!/bin/bash -e
# Generate SSL certificate

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

# Exit if openssl is not available
which openssl >/dev/null || fatal "openssl is not installed"

# Use turnkey-make-ssl-cert to generate default server cert
turnkey-make-ssl-cert -d

# Restart relevant installed services
which apache2 >/dev/null && service apache2 restart
which nginx >/dev/null && service nginx restart
which lighttpd >/dev/null && service nginx restart
which stunnel4 >/dev/null && service stunnel4 restart
which tomcat7 >/dev/null && service tomcat7 restart 

# final tidy up
update-ca-certificates

