#!/bin/bash -ex

# adminer-mysql
#
# Only show MySQL
sed -i '/^.*\$tkl_server/ s|DB_DESC|MySQL|' /etc/adminer/tkl-index.php
sed -i '/^.*\$tkl_database/ s|DRIVER|server|' /etc/adminer/tkl-index.php

# Create root-like adminer MySQL user account
service mysql start || service mariadb start
ADMIN_PWORD=$(mcookie)
mysql <<EOF
USE mysql;
GRANT ALL PRIVILEGES ON *.* to 'adminer'@localhost IDENTIFIED BY '$ADMIN_PWORD' WITH GRANT OPTION;
EOF
service mysql stop || service mariadb stop

# Enable Adminer MySQL user password inithook
chmod +x /usr/lib/inithooks/firstboot.d/35adminer-mysqlpass
