#!/bin/bash -ex

# Ensure redirection is enabled
sed -i 's|^[[:space:]]*#([[:space:]]*"mod_redirect".*)|\1|' /etc/lighttpd/lighttpd.conf

# Link conf file to available-sites, and enable it
ln -s /etc/adminer/lighttpd.conf /etc/lighttpd/conf-available/50-adminer.conf
lighty-enable-mod adminer || true
lighty-enable-mod accesslog
