#!/bin/sh -e

# adminer-mysql
#
#   configure adminer to only show mysql, and to link the common theme

ADMINER_DIR=/usr/share/adminer
PLUGINS_DIR=$ADMINER_DIR/plugins
STATIC_DIR=$ADMINER_DIR/adminer/static
THEME_FILE=$STATIC_DIR/default.css
TKL_INDEX=$ADMINER_DIR/adminer/tkl-index.php
TKL_THEME=$ADMINER_DIR/designs/nette/adminer.css


# Enable nette theme 
mv $THEME_FILE $STATIC_DIR/default.css.bak
ln -s $TKL_THEME $THEME_FILE  

# Enable only MySQL
sed -i '/^.*\$tkl_server/ s|DB_DESC|MySQL|' $TKL_INDEX
sed -i '/^.*\$tkl_database/ s|DRIVER|server|' $TKL_INDEX

# Create root-like adminer MySQL user account
service mysql start
ADMIN_PWORD=$(mcookie)
mysql <<EOF
USE mysql;
GRANT ALL ON *.* to 'adminer'@localhost IDENTIFIED BY '$ADMIN_PWORD';
EOF
service mysql stop

# Enable Adminer MySQL user password inithook
chmod +x /usr/lib/inithooks/firstboot.d/35adminer-mysqlpass
