#!/bin/bash -ex

# adminer-pgsql
#
# Only show Postgres
sed -i '/^.*\$tkl_server/ s|DB_DESC|PostgreSQL|' /etc/adminer/tkl-index.php
sed -i '/^.*\$tkl_database/ s|DRIVER|pgsql|' /etc/adminer/tkl-index.php
