#!/bin/sh -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src
WEBROOT=/var/www/ajaxplorer
ADMIN_PASS=turnkey

VERSION="stable-channel/4.2.3/ajaxplorer-core-4.2.3.tar.gz"
URL="http://sourceforge.net/projects/ajaxplorer/files/ajaxplorer/$VERSION"

# download and unpack
dl $URL $SRC
tar -zxf $SRC/ajaxplorer-core-*.tar.gz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/ajaxplorer-core-* $WEBROOT

# apply customization overlay
cp -TdR $SRC/ajaxplorer.overlay $WEBROOT
chown -R www-data:www-data $WEBROOT/data

# initial setup
lighty-enable-mod fastcgi
lighty-enable-mod fastcgi-php
/etc/init.d/lighttpd start
curl http://127.0.0.1/index.php?ignore_tests=true >/dev/null
/etc/init.d/lighttpd stop

# set initial admin local password
/usr/lib/inithooks/bin/ajaxplorer.py --pass=$ADMIN_PASS

# cleanup
rm -rf $SRC/ajaxplorer*

