#!/bin/bash -ex

CONF="/etc/apache2/conf-available/security.conf"

if [ -e $CONF ]; then
    # Set apache production security
    sed -i "s|^ServerTokens\(.*\)|ServerTokens Prod|" $CONF
    sed -i "s|^ServerSignature\(.*\)|ServerSignature Off|" $CONF

    # Disable HTTP compression when using SSL to protect against BREACH
    sed -i '/<\/Directory>/ a \
\
# Disable HTTP compression when using SSL to protect against BREACH\
<Location />\
  SetEnvIfExpr "%{HTTPS} == '"'"'on'"'"'" no-gzip\
</Location>
' $CONF

    a2enconf security
fi
