#!/bin/bash -ex

dl() {
    cd $2; curl -L -f -O $1; cd -
}

VERSION="4.0.2"
URL="http://download.cksource.com/CKEditor/CKEditor/CKEditor%20${VERSION}/ckeditor_${VERSION}_standard.tar.gz"

dl $URL /usr/local/src

