#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="4.0.2"
URL="https://download.cksource.com/CKEditor/CKEditor/CKEditor%20${VERSION}/ckeditor_${VERSION}_standard.tar.gz"

dl $URL /usr/local/src

