#!/bin/bash -ex

REPOS=/srv/repos
HELLOWORLD=/usr/local/src/helloworld

mkdir -p $REPOS

esc() {
    echo $1 | sed "s/\//\\\\\//g"
}

#used by git, bzr, hg
dvcs_repo() {
    TARGET=$REPOS/$1/helloworld
    mkdir -p $TARGET
    cd $TARGET
    $1 init
    cp $HELLOWORLD/* $TARGET
    FILE=$TARGET/helloworld.py
    sed -i "s/world/wordl/" $FILE && $1 add . && $1 commit -m "initial commit"
    sleep 2 # workaround for damn hg checking modification times!!
    sed -i "s/wordl/world/" $FILE && $1 add . && $1 commit -m "fixed typo"
}

# create git repo
export GIT_COMMITTER_EMAIL=root@localhost
export GIT_AUTHOR_EMAIL=root@localhost
dvcs_repo git

touch $REPOS/git/helloworld/.git/git-daemon-export-ok
GITPUB=/var/lib/git
ln -s $REPOS/git/helloworld/.git $GITPUB/helloworld.git
ln -s $GITPUB $REPOS/git/public
echo "Hello World" > $REPOS/git/helloworld/.git/description

sed -i "/GIT_DAEMON_ENABLE/ s/false/true/" /etc/default/git-daemon

# configure bzr repo
export BZR_EMAIL=root@localhost
dvcs_repo bzr

cd /etc/init.d
update-rc.d bzr defaults

# create mercurial repo
export EMAIL=root@localhost
dvcs_repo hg

cat >$REPOS/hg/helloworld/.hg/hgrc<<EOF
[web]
contact = root@localhost
description = Hello World
EOF

cat >/etc/mercurial/hgweb.config<<EOF
[web]
style = git-web

[collections]
/srv/repos/hg/ = /srv/repos/hg/
EOF

cp /usr/share/doc/mercurial/examples/hgweb.cgi /usr/lib/cgi-bin
chmod +x /usr/lib/cgi-bin/hgweb.cgi
ln -s /etc/mercurial/hgweb.config /usr/lib/cgi-bin/hgweb.config

sed -i "s|^config = \(.*\)|config = \"hgweb.config\"|" /usr/lib/cgi-bin/hgweb.cgi

# create subversion repo
TARGET=$REPOS/svn/helloworld

mkdir -p $TARGET
svnadmin create $TARGET

mkdir -p /tmp/svn/{branches,tags,trunk}
cp $HELLOWORLD/* /tmp/svn/trunk
sed -i "s/world/wordl/" /tmp/svn/trunk/helloworld.py
svn import /tmp/svn file://$TARGET -m "initial commit"
rm -rf /tmp/svn && svn checkout file://$TARGET /tmp/svn
sed -i "s/wordl/world/" /tmp/svn/trunk/helloworld.py
svn commit /tmp/svn -m "fixed typo"
rm -rf /tmp/svn

cd /etc/init.d
update-rc.d svnserve defaults


# cleanup
rm -rf $HELLOWORLD

