#!/bin/bash -ex

REPOS=/srv/repos
HELLOWORLD=/usr/local/src/helloworld

mkdir -p $REPOS

# create git repo
export GIT_COMMITTER_EMAIL=root@localhost
export GIT_AUTHOR_EMAIL=root@localhost

TARGET=$REPOS/git/helloworld
mkdir -p $TARGET
cd $TARGET
git init
cp $HELLOWORLD/* $TARGET
FILE=$TARGET/helloworld.py
sed -i "s/world/wordl/" $FILE && git add . && git commit -m "initial commit"
sed -i "s/wordl/world/" $FILE && git add . && git commit -m "fixed typo"

touch $REPOS/git/helloworld/.git/git-daemon-export-ok
GITPUB=/var/lib/git
git clone --bare $REPOS/git/helloworld $GITPUB/helloworld.git
ln -s $GITPUB $REPOS/git/public
echo "Hello World" > $REPOS/git/helloworld/.git/description

sed -i "/GIT_DAEMON_ENABLE/ s/false/true/" /etc/default/git-daemon
chown -R www-data:root $GITPUB

# create subversion repo
TARGET=$REPOS/svn/helloworld

mkdir -p $TARGET
svnadmin create $TARGET

mkdir -p /tmp/svn/{branches,tags,trunk}
cp $HELLOWORLD/* /tmp/svn/trunk
sed -i "s/world/wordl/" /tmp/svn/trunk/helloworld.py
svn import /tmp/svn file://$TARGET -m "initial commit"
rm -rf /tmp/svn && svn checkout file://$TARGET /tmp/svn
sed -i "s/wordl/world/" /tmp/svn/trunk/helloworld.py
svn commit /tmp/svn -m "fixed typo"
rm -rf /tmp/svn

cd /etc/init.d
update-rc.d svnserve defaults

# cleanup
rm -rf $HELLOWORLD

# create vcs user
useradd -d /srv/repos vcs
chown -R vcs:vcs /srv/repos
