#!/bin/sh -ex

STORAGE=/srv/storage
EXTPLORER_WWWROOT=/var/www/extplorer
EXTPLORER_PASS=turnkey

# unpack and configure extplorer
unzip /usr/local/src/eXtplorer_*.zip -d $EXTPLORER_WWWROOT
chown www-data:www-data $EXTPLORER_WWWROOT/ftp_tmp
chown www-data:www-data $EXTPLORER_WWWROOT/config/.htusers.php

tar -zxf $EXTPLORER_WWWROOT/scripts.tar.gz -C $EXTPLORER_WWWROOT
find $EXTPLORER_WWWROOT/scripts -type f -exec chmod 644 {} \;
find $EXTPLORER_WWWROOT/scripts -type d -exec chmod 755 {} \;
rm -f $EXTPLORER_WWWROOT/scripts.tar.gz

rm -f /usr/local/src/eXtplorer_*.zip

# enable fastcgi in lighttpd for extplorer
lighty-enable-mod fastcgi

# configure extplorer users
MD5_PASS=$(echo -n $EXTPLORER_PASS | md5sum | cut -d " " -f 1)
cat >$EXTPLORER_WWWROOT/config/.htusers.php<<EOF
<?php
/** ensure this file is being included by a parent file */
defined( "_VALID_MOS" ) or die( "Direct Access to this location is not allowed." );

\$GLOBALS["users"]=array(
  array("admin","$MD5_PASS","$STORAGE","http://localhost",1,"",7,1),
  array("guest","$MD5_PASS","$STORAGE","http://localhost",0,"",0,1),
);
?>
EOF

# urge user to change default admin password
sed -i "s|extEncodePassword('admin')|extEncodePassword('$EXTPLORER_PASS')|" $EXTPLORER_WWWROOT/scripts/application.js.php

sed -i "s|admin with password admin|admin with password $EXTPLORER_PASS|" $EXTPLORER_WWWROOT/languages/*.php

# credit link on login page
CREDIT_HEAD="<style type='text/css'> #turnkey-credit { font-family: Tahoma,Sans,Arial,Helvetica,Verdana,sans-serif; font-size: 11px; text-align: center; padding-top: 20px; } #turnkey-credit a { text-decoration: none; } #turnkey-credit a:hover { text-decoration: underline; } </style>\n"

CREDIT_BODY="<div id='turnkey-credit'><a href='http://www.turnkeylinux.org/$HOSTNAME'>$CREDIT_ANCHORTEXT</a> - Powered by <a href='http://www.turnkeylinux.org'>TurnKey Linux</a></div>\n"

ENDBODY="<div class=\"x-box-bc\"></div></div></div>"

sed -i "s|</head>|$CREDIT_HEAD</head>|" $EXTPLORER_WWWROOT/index.php
sed -i "s|$ENDBODY|$ENDBODY\n$CREDIT_BODY|" $EXTPLORER_WWWROOT/include/login.php

# add www-data user to users group so admin can upload to storage
adduser www-data users

# allow root to connect to ftp (its local)
sed -i "s|^root|#root|" /etc/ftpusers

