#!/bin/sh -e

# enable fastcgi modules
lighty-enable-mod fastcgi || true
lighty-enable-mod fastcgi-php || true

# minimize fastcgi children
sed -i '/max-procs/ s/=>.*/=> 1,/; /PHP_FCGI_CHILDREN/ s/=>.*/=> "1",/g' /etc/lighttpd/conf-available/*fastcgi*

# load mod_setenv
sed -i '/server.modules = (/a \\t"mod_setenv",' /etc/lighttpd/lighttpd.conf
