#!/bin/sh -e

# enable fastcgi modules
lighty-enable-mod fastcgi
lighty-enable-mod fastcgi-php

# minimize fastcgi children
sed -i '/max-procs/ s/=>.*/=> 1,/; /PHP_FCGI_CHILDREN/ s/=>.*/=> "1",/g' /etc/lighttpd/conf-available/*fastcgi*

