#!/bin/sh -ex

# Conf script to configure LigHTTPd webserver
#
# To use with php-fpm, ensure that conf/php-fpm script is also run

# Remove default webroot
rm -r /var/www/html

# Disable default unconfigured site
lighty-disable-mod unconfigured

# load mod_setenv
sed -i '\|server.modules = (|a \\t"mod_setenv",' /etc/lighttpd/lighttpd.conf
