#!/bin/sh -e

set ${MERCURIAL_PORT:=8080}

echo Listen $MERCURIAL_PORT >> /etc/apache2/ports.conf

cat >/etc/mercurial/apache.conf<<EOF
ServerName localhost

<VirtualHost *:$MERCURIAL_PORT>
    UseCanonicalName Off
    ServerAdmin  webmaster@localhost
    AddHandler cgi-script .cgi
    ScriptAliasMatch ^(.*) /usr/lib/cgi-bin/hgweb.cgi/\$1
</VirtualHost>
EOF

ln -s /etc/mercurial/apache.conf /etc/apache2/sites-available/mercurial.conf
a2ensite mercurial

