#!/bin/bash -e

# download mysqltuner
dl() {
    if [[ "$FAB_HTTP_PROXY" ]]; then
       PROXY=(--proxy "$FAB_HTTP_PROXY")
    fi
    cd "$2"
    curl -L -f -O "${PROXY[@]}" "$1"
    cd -
}

# Install mysqltuner at "latest" tag (via gh_releases) and from core dev's
# repo[1] - rather than separate "org" repo[2]
#
# [1] https://github.com/jmrenouard/MySQLTuner-perl
# [2] https://github.com/major/MySQLTuner-perl
BIN=/usr/local/bin
VERSION=$(gh_releases jmrenouard/MySQLTuner-perl | sort -V | tail -1)
REPO="jmrenouard/MySQLTuner-perl"
URL="https://raw.githubusercontent.com/$REPO/refs/tags/$VERSION"
dl "$URL/mysqltuner.pl" $BIN
mv "$BIN/mysqltuner.pl" $BIN/mysqltuner
chmod +x "$BIN/mysqltuner"
dl "$URL/basic_passwords.txt" $BIN
dl "$URL/vulnerabilities.csv" $BIN

# As of Debian Buster, there is no longer a /etc/init.d/mysql script, so let's
# link the mariadb one.
ln -s /etc/init.d/mariadb /etc/init.d/mysql

# secure mysql installation
service mysql start
mysql <<EOF
USE mysql;
# remove anonymous users
DELETE FROM user WHERE User='';

# remove remote root
DELETE FROM user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');

# remove test database
DROP DATABASE IF EXISTS test;
DELETE FROM db WHERE Db='test' OR Db='test\\_%';
EOF
service mysql stop
