#!/bin/bash -ex

# hack for node-inspector
# https://github.com/node-inspector/node-inspector/issues/777
npm install -g --unsafe-perm node-inspector

GLOBALS='bower pm2 forever grunt grunt-cli nsp'

for package in $GLOBALS; do
	npm install -g $package
done

USER=node

PM2_BIN=/usr/local/lib/node_modules/pm2/bin/pm2 
PM2_PATH=/home/$USER/.pm2/
PM2_LOG=/var/log/pm2-$USER

adduser --system --group --shell /bin/bash $USER

mkdir -p $PM2_PATH
echo '[]' > $PM2_PATH/dump.pm2

mkdir -p $PM2_LOG
ln -s $PM2_LOG $PM2_PATH/logs
ln -s $PM2_LOG/pm2.log $PM2_PATH/pm2.log

chown -R $USER:$USER $PM2_PATH $PM2_LOG

rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/nodejs /etc/nginx/sites-enabled/nodejs

update-rc.d pm2 defaults

rm -rf /tmp/npm*

