#!/bin/sh -ex

SRC=/usr/local/src

# unpack and install node (if pre-build is available, use it)
if [ -e $SRC/node-*-build.tar.gz ]; then
    tar -zxf $SRC/node-*-build.tar.gz -C $SRC
    cd $SRC/node-*
    make install
else
    tar -zxf $SRC/node-*.tar.gz -C $SRC
    cd $SRC/node-*
    ./configure
    make
    make install
fi

# npm completion
npm completion > /etc/skel/.bashrc.d/npm
chmod +x /etc/skel/.bashrc.d/npm
cp /etc/skel/.bashrc.d/npm /root/.bashrc.d/npm

# cleanup
rm -rf $SRC/node-*

