#!/bin/bash -ex

# hack for node-inspector
# https://github.com/node-inspector/node-inspector/issues/777
npm install -g --unsafe-perm node-inspector

GLOBALS='bower grunt grunt-cli nsp'

for package in $GLOBALS; do
	npm install -g $package
done

rm -rf /tmp/npm*
rm -f /etc/nginx/sites-enabled/default
