#!/bin/bash -ex

SRC=/usr/local/src

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

dl http://nodejs.org/dist/latest/SHASUMS256.txt $SRC

TARBALL_RE="linux-x${FAB_ARCH: -2:2}.tar.gz"
TARBALL=$(grep $TARBALL_RE $SRC/SHASUMS256.txt | awk '{ print $2 }')
dl http://nodejs.org/dist/latest/${TARBALL} $SRC

grep $TARBALL $SRC/SHASUMS256.txt > $SRC/$TARBALL.sha256
cd $SRC
sha256sum -c $TARBALL.sha256
rm SHASUMS256.txt $TARBALL.sha256

tar -zxf $SRC/$TARBALL -C $SRC
rm $SRC/$TARBALL
ln -s $SRC/node-v* $SRC/node

for f in $(ls $SRC/node/bin); do
    ln -s $SRC/node/bin/$f /usr/local/bin/$f
done

# npm completion
npm completion > /etc/skel/.bashrc.d/npm
chmod +x /etc/skel/.bashrc.d/npm
cp /etc/skel/.bashrc.d/npm /root/.bashrc.d/npm

