#!/bin/bash -ex

# install n node version manager
cd /usr/local/src
git clone https://github.com/tj/n
cd n && make install

# install latest stable node
n stable

# user-global npm installation: we don't need root for npm global installs

cat > /etc/skel/.bashrc.d/nodejs <<'EOF'
export NPM_PACKAGES="$HOME/.npm-packages"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
export PATH="$NPM_PACKAGES/bin:$PATH"
EOF

chmod +x /etc/skel/.bashrc.d/nodejs

echo 'prefix=${HOME}/.npm-packages' > /etc/skel/.npmrc

# npm completion
npm completion > /etc/skel/.bashrc.d/npm
chmod +x /etc/skel/.bashrc.d/npm
cp /etc/skel/.bashrc.d/npm /root/.bashrc.d/npm


