#!/bin/sh -ex

set ${PGSQL_PASS:=postgres}

PGSQL_VER=$(ls /etc/postgresql/)
CONF_DIR=/etc/postgresql/${PGSQL_VER}/main

# Recreate postgres and templates using UTF-8
pg_dropcluster --stop ${PGSQL_VER} main
pg_createcluster --start -e UTF-8 ${PGSQL_VER} main
/etc/init.d/postgresql stop

# Enable password encryption
sed -i "/^#password_encryption = on/ s/#//" $CONF_DIR/postgresql.conf

# Reduce shared_buffers (better than increasing /proc/sys/kernel/shmmax)
sed -i "/^shared_buffers =/ s/32/24/" $CONF_DIR/postgresql.conf

# Configure postgres password
/etc/init.d/postgresql start

su postgres -c 'psql postgres' << EOF
alter user postgres with encrypted password '$PGSQL_PASS';
EOF

# give user root superuser privileges over postgres
su postgres -c "createuser --superuser root"
su postgres -c "createdb root"

/etc/init.d/postgresql stop
