#!/bin/sh -e

PMA_USER=pma
PMA_PASS=pmapass

# start mysql
/etc/init.d/mysql start

# create pma user for advanced features
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
GRANT SELECT (
    Host, User, Select_priv, Insert_priv, Update_priv, Delete_priv,
    Create_priv, Drop_priv, Reload_priv, Shutdown_priv, Process_priv,
    File_priv, Grant_priv, References_priv, Index_priv, Alter_priv
    ) ON mysql.user TO '$PMA_USER'@'localhost';
GRANT SELECT (
    Host, User, Select_priv, Insert_priv, Update_priv, Delete_priv,
    Create_priv, Drop_priv, Reload_priv, Shutdown_priv, Process_priv,
    File_priv, Grant_priv, References_priv, Index_priv, Alter_priv,
    Show_db_priv, Super_priv, Create_tmp_table_priv, Lock_tables_priv,
    Execute_priv, Repl_slave_priv, Repl_client_priv
    ) ON mysql.user TO '$PMA_USER'@'localhost';
GRANT SELECT ON mysql.db TO '$PMA_USER'@'localhost';
GRANT SELECT ON mysql.host TO '$PMA_USER'@'localhost';
GRANT SELECT (Host, Db, User, Table_name, Table_priv, Column_priv)
    ON mysql.tables_priv TO '$PMA_USER'@'localhost';
EOF

# create phpmyadmin linked-tables database
PMADB_SQL=/usr/share/doc/phpmyadmin/examples/create_tables.sql.gz
zcat $PMADB_SQL | mysql --user=root --password=$MYSQL_PASS --batch

# give pma user permissions to phpmyadmin db and set password
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
GRANT SELECT, INSERT, UPDATE, DELETE ON phpmyadmin.*
TO '$PMA_USER'@'localhost' IDENTIFIED BY '$PMA_PASS'; flush privileges;
EOF

# stop mysql
/etc/init.d/mysql stop

# update phpmyadmin with pmapass
CONF=/etc/phpmyadmin/config.inc.php
sed -i "s|\['controlpass'\]\(.*\)|\['controlpass'\] = '$PMA_PASS';|" $CONF

# set the proper URI
echo "\$cfg['PmaAbsoluteUri'] = 'https://0.0.0.0:12322/';" >> $CONF

# change the announced web access port
sed -i 's|80|12322|' /etc/phpmyadmin/phpmyadmin.service
