#!/bin/sh -e

echo Listen 12322 >> /etc/apache2/ports.conf
ln -s /etc/phpmyadmin/apache.conf /etc/apache2/sites-available/phpmyadmin.conf
a2ensite phpmyadmin

# add mcrypt support to apache2 (if not already configured)
debconf-set-selections << END
php5-mcrypt php5/extension_mcrypt_apache2 boolean true
END

DEBIAN_FRONTEND=noninteractive dpkg-reconfigure php5-mcrypt
