#!/bin/sh -e

# Disable extra_login_security in phppgadmin
sed -i "/\$conf\['extra_login_security'\]/ s/=.*/= false;/" \
    /etc/phppgadmin/config.inc.php

# Remove apache configuration symlink and stop upgrades creating it again
rm -f /etc/apache2/conf-available/phppgadmin.conf
touch /etc/apache2/conf-available/phppgadmin.conf

