#!/bin/bash -ex

if [ $HOSTNAME ]; then
    APPNAME=$HOSTNAME
    [ "$APPNAME" == "rails" ] && APPNAME=railsapp ## namespace conflict
else
    echo "'$(basename $0)' error: hostname not defined"
    return 1
fi

DB_USER=$APPNAME
DB_PASS=$(mcookie)
WEBROOT=/var/www/$APPNAME

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

# install ruby-enterprise
RUBYENT=http://rubyenterpriseedition.googlecode.com/files
[ $I386 ] && RUBYENT=$RUBYENT/ruby-enterprise_1.8.7-2012.02_i386_ubuntu10.04.deb
[ $AMD64 ] && RUBYENT=$RUBYENT/ruby-enterprise_1.8.7-2012.02_amd64_debian6.0.deb
dl $RUBYENT /usr/local/src
DEBIAN_FRONTEND=noninteractive dpkg -i /usr/local/src/ruby-enterprise*.deb
rm /usr/local/src/ruby-enterprise*.deb

# uninstall gems installed by ruby-enterprise
for g in $(ls /usr/local/lib/ruby/gems/*/cache); do
    GEM_NAME=$(echo $g | sed "s|-\(.*\).gem||")
    gem uninstall -a -I -x -n /usr/local/bin $GEM_NAME
done
rm -f /usr/local/lib/ruby/gems/*/cache/*.gem

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
GEMOPTS="--no-rdoc --no-ri"
gem install $GEMOPTS passenger
gem install $GEMOPTS rake
gem install $GEMOPTS rails
gem install $GEMOPTS bundler
gem install $GEMOPTS mysql -- --with-mysql-config='/usr/bin/mysql_config'
gem install $GEMOPTS execjs
gem install $GEMOPTS therubyracer

# build and configure passenger
passenger-install-apache2-module --auto
PASSENGER=$(echo $(basename $(ls -d /usr/local/lib/ruby/gems/*/gems/passenger*)))
sed -i "s|PASSENGER|$PASSENGER|g" /etc/apache2/conf.d/passenger

# convenience execution variables
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

# start mysql server
/etc/init.d/mysql start

# create databases for each environment
for DB_ENV in test development production; do
    DB_NAME=${APPNAME}_${DB_ENV}
    $MYSQL_ADMIN create $DB_NAME --default-character-set=utf8;
    $MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"
done

# seed rails application (3.x requires new)
cd /var/www
if $(rails --version | grep -q "Rails 2.3"); then
    rails $APPNAME -d mysql --skip
else
    rails new $APPNAME -d mysql --skip
fi
unset HTTP_PROXY

CONF=$WEBROOT/config/database.yml
sed -i "s|username:.*|username: $DB_USER|g" $CONF
sed -i "s|password:.*|password: $DB_PASS|g" $CONF

# configure permissions
chown -R root:www-data $WEBROOT
chown -R www-data:www-data $WEBROOT/tmp
chown -R www-data:www-data $WEBROOT/log

# apache configuration
a2enmod rewrite
a2enmod proxy_balancer
a2enmod proxy_http
a2enmod proxy
a2enmod headers

a2dissite default

mv /etc/apache2/conf/rails.conf /etc/apache2/conf/$APPNAME.conf
sed -i "s|@APPNAME@|$APPNAME|g" /etc/apache2/conf/$APPNAME.conf

mv /etc/apache2/sites-available/rails /etc/apache2/sites-available/$APPNAME
sed -i "s|@APPNAME@|$APPNAME|g" /etc/apache2/sites-available/$APPNAME

a2ensite $APPNAME

# stop mysql server
/etc/init.d/mysql stop

