#!/bin/bash -ex

SRC=/usr/local/src
WEBROOT=/var/www/webdavcgi
GIT_SOURCE=https://github.com/DanRohde/webdavcgi.git
TAG_RELEASE=40a9e02694ad8c554307250e51d64d1cce7bb76d

git clone $GIT_SOURCE $WEBROOT

cd $WEBROOT
git checkout $TAG_RELEASE
rm -R $WEBROOT/.git

mv $SRC/webdav.conf $WEBROOT
mv $SRC/logout $WEBROOT/cgi-bin

chmod a+rx $WEBROOT $WEBROOT/cgi-bin
chmod -R a+r $WEBROOT

echo yes | perl -MCPAN -e 'install DateTime::Format::Human::Duration'

cpan install List::MoreUtils
cpan install IO::Compress::Brotli

apt-get -y remove build-essential
apt-get -y autoremove


a2enmod rewrite
a2enmod cgi
a2enmod authnz_external

