#!/bin/sh -ex

fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }

TOMCAT=tomcat7

CATALINA_HOME="/usr/share/$TOMCAT"
CATALINA_BASE="/var/lib/$TOMCAT"
CATALINA_TMPDIR="$CATALINA_BASE/temp"

# identify JVM to use
##We have to check 5 conditions, Sun6, Oracle 6 and 7, openjdk 6 and 7
[ -e /usr/lib/jvm/java-6-sun ] && JVM=java-6-sun
[ -e /usr/lib/jvm/java-6-oracle ] && JVM=java-6-oracle
[ -e /usr/lib/jvm/java-7-oracle ] && JVM=java-7-oracle

[ -e /usr/lib/jvm/java-7-openjdk-i386 ] && JVM=java-7-openjdk-i386
[ -e /usr/lib/jvm/java-7-openjdk-amd64 ] && JVM=java-7-openjdk-amd64

[ -z "$JVM" ] && fatal "JVM to use could not be identified"

# configure java/tomcat environment
cat >> /etc/environment<<EOF
CATALINA_HOME="$CATALINA_HOME"
CATALINA_BASE="$CATALINA_BASE"
CATALINA_OPTS="-server -Xms384M -Xmx512M -XX:MaxPermSize=256M"
JAVA_HOME="/usr/lib/jvm/${JVM}"
EOF

# this may not be 100% safe
JINFO=`ls /usr/lib/jvm/.*java*7*jinfo`
JINFO=${JINFO%.jinfo}
JINFO=${JINFO#*.}
# not sure if this is actually needed
update-java-alternatives --jre-headless -s $JINFO
sed -i "s/^#JAVA_HOME.*/JAVA_HOME=\/usr\/lib\/jvm\/${JVM}/" /etc/default/$TOMCAT

# configure Apache if needed (Jk connector to Tomcat)
if [ -e /etc/apache2/sites-available/jktomcat.conf ]; then
    a2dissite 000-default
    a2ensite jktomcat
fi

# from https://bugs.launchpad.net/ubuntu/+source/tomcat7/+bug/1232258
create_link() {
    ln -s $CATALINA_BASE/$1 $CATALINA_HOME/$1
}
create_link common
create_link server
create_link shared
create_link conf
create_link logs
mkdir -p $CATALINA_TMPDIR
chown $TOMCAT $CATALINA_TMPDIR

