#!/bin/sh -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src
W2PPASS=turnkey
W2PROOT=/var/www/web2py
WSGI=$W2PROOT/wsgihandler.py

# clone web2py
cd /var/www
RELEASES="$(/usr/local/bin/gh_releases web2py/web2py)"
VER=$(echo "${RELEASES}" | sort --version-sort | tail -1)
git clone --recursive --branch $VER https://github.com/web2py/web2py

# Install GitPython in virtualenv to workaround turnkey-pylib
# git.py conflict
virtualenv -p python2 $W2PROOT/venv2
$W2PROOT/venv2/bin/pip install GitPython

# Also install py3 venv - to add support for python3
virtualenv -p python3 $W2PROOT/venv3

# Use python2 by default for now
ln -s $W2PROOT/venv2 $W2PROOT/venv

chown -R www-data:www-data $W2PROOT

# copy wsgihandler to web2py root
cp $W2PROOT/handlers/wsgihandler.py $WSGI

# Add code for entering virtualenv after wsgihandler is started
#
# Insert placeholders
sed -i 's|import os|import os\n\nLINE_1\nLINE_2\nLINE_3|' $WSGI
# Insert proper lines
sed -i "s|LINE_1|activate_this = '$W2PROOT/venv/bin/activate_this.py'|" $WSGI
sed -i "s|LINE_2|with open(activate_this, 'rb') as fob:|" $WSGI
sed -i "s|LINE_3|    exec(compile(fob.read(), activate_this, 'exec'), dict(__file__=activate_this))|" $WSGI

# create web2py admin interface password
/usr/lib/inithooks/bin/web2py.py --pass=$W2PPASS

# configure apache
a2dissite 000-default
a2ensite web2py
a2enmod rewrite
