#!/bin/sh -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src
W2PPASS=turnkey
W2PROOT=/var/www/web2py

# clone web2py
cd /var/www
RELEASES="$(/usr/local/bin/gh_releases web2py/web2py)"
VER=$(echo "${RELEASES}" | sort --version-sort | tail -1)
git clone --recursive --branch $VER https://github.com/web2py/web2py

# Install GitPython in virtualenv to workaround turnkey-pylib
# git.py conflict
virtualenv $W2PROOT/venv
$W2PROOT/venv/bin/pip install GitPython

chown -R www-data:www-data $W2PROOT

# copy wsgihandler to web2py root
cp $W2PROOT/handlers/wsgihandler.py $W2PROOT/wsgihandler.py

# Code for entering virtualenv after wsgihandler is started
VIRTUALENV_ACTIVATE_PATH='/var/www/web2py/venv/bin/activate_this.py'
VIRTUALENV_ACTIVATE="activate_this = '$VIRTUALENV_ACTIVATE_PATH'\nexecfile(activate_this, dict(__file__=activate_this))"

# Insert code just below initial imports
sed -i "s|import os|import os\n\n$VIRTUALENV_ACTIVATE|" $W2PROOT/wsgihandler.py

# create web2py admin interface password
/usr/lib/inithooks/bin/web2py.py --pass=$W2PPASS

# configure apache
a2dissite 000-default
a2ensite web2py
a2enmod rewrite

