#!/bin/sh
set -e

#
# List the soft prerequisites here.  This is a space separated list of
# names, of scripts that are in the same directory as this one, that
# must be run before this one can be.
#
PREREQS=""
case $1 in
    prereqs) echo "$PREREQS"; exit 0;;
esac

. /usr/share/initramfs-tools/hook-functions

# XXX: tail and realpath are included by default, right?
#copy_exec /usr/bin/realpath
#copy_exec /usr/bin/tail
copy_exec /sbin/blkid
copy_exec /bin/lsblk
copy_exec /sbin/parted
copy_exec /sbin/partprobe
copy_exec /sbin/resize2fs
