#!/bin/bash -e

# filename:	/usr/local/sbin/oracle-java-installer
# documenation:	http://www.webupd8.org/2012/06/how-to-install-oracle-java-7-in-debian.html                                        
#
# you can safely ':s/java7/java8'
# you might need to `apt-get remove oracle-java7-installer` afterwards

# define repos
echo "# http://www.webupd8.org/2012/06/how-to-install-oracle-java-7-in-debian.html" > /etc/apt/sources.list.d/webupd8team-java.list
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" >> /etc/apt/sources.list.d/webupd8team-java.list         
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" >> /etc/apt/sources.list.d/webupd8team-java.list     
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
apt-get update

# accept Oracle license
echo "oracle-java7-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections

# perform the install
apt-get install oracle-java7-installer oracle-java7-set-default
