# Fail2Ban filter for adminer
#
# Provided by TurnKey GNU/Linux
# Works for Apache2, LigHTTPd & Nginx access logs

[INCLUDES]
before = common.conf

[Definition]
failregex = ^<HOST> .* "POST /adminer\.php.*" (200|302) .*$

ignoreregex =
