# This is a custom shared hardened SSL conf provided by TurnKey
# created 2025-20-11 using guidance from Mozilla Guideline v5.7
# https://ssl-config.mozilla.org/#server=lighttpd&version=1.4.79&config=intermediate&openssl=3.5.1&guideline=5.7
# By default this file is sourced by /etc/lighttpd/conf-available/10-ssl.conf

ssl.pemfile = "/etc/ssl/private/cert.pem"
ssl.privkey = "/etc/ssl/private/cert.key"
ssl.dh-file = "/etc/ssl/private/dhparams.pem"

ssl.openssl.ssl-conf-cmd = ("MinProtocol" => "TLSv1.2")
# lighttpd 1.4.79 TLS default appends X448
#ssl.openssl.ssl-conf-cmd += ("Curves" => "X25519:prime256v1:secp384r1")

# lighttpd TLS defaults are widely supported by clients and should be preferred.
# See https://wiki.lighttpd.net/Docs_SSL
# Uncomment to better match the less restricted Mozilla intermediate spec.
# (TKL Ciphers set by common/conf/turnkey.d/zz-ssl-ciphers)
#ssl.openssl.ssl-conf-cmd += ("CipherString" => "ZZ_SSL_CIPHERS")

# HSTS config + additional hardening
server.modules += ("mod_redirect")
server.modules += ("mod_setenv")
$HTTP["scheme"] == "https" {
  # HTTP Strict Transport Security (63072000 seconds)
  setenv.add-response-header = (
    "Strict-Transport-Security" => "max-age=63072000; includeSubdomains; preload",
    "X-Frame-Options" => "DENY",
    "X-Content-Type-Options" => "nosniff",
  )
}
else $HTTP["scheme"] == "http" {
    url.redirect = ("" => "https://${url.authority}${url.path}${qsa}")
}

# OCSP stapling config (disabled by default)

# OCSP stapling (input file is maintained by external 'cert-staple.sh' script)
# https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_SSL#OCSP-Stapling
#ssl.stapling-file = "/etc/ssl/private/cert-staple.der"
