#!/bin/bash -e
# regenerate debian-sys-maint mysql password

. /etc/default/inithooks

if [ -f /etc/mysql/debian.cnf ]; then
    PASSWORD=$(mcookie | head -c 16)
    $INITHOOKS_PATH/bin/mysqlconf.py --user debian-sys-maint --pass="$PASSWORD"
else
    dpkg-reconfigure -f noninteractive mysql-server-5.5
fi
