#!/bin/bash -e
# set mysql root password

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
if [ -z "${DB_PASS}" ]; then
	DB_PASS=$(mcookie);
	$INITHOOKS_PATH/bin/mysqlconf.py --user=root --pass="$DB_PASS";
	echo $DB_PASS > ~/mysql_pass;
else
	$INITHOOKS_PATH/bin/mysqlconf.py --user=root --pass="$DB_PASS";
fi

