function f(){this.b=[];this.f=0}f.prototype.clear=function(){this.b=[];this.f=0};f.prototype.put=function(a){this.b.push(a)};f.prototype.get=function(){var a;this.b.length&&(a=this.b[this.f],2*++this.f>=this.b.length&&(this.b=this.b.slice(this.f),this.f=0));return a};function h(){this.b=new f}h.prototype=[];h.prototype.remove=function(a){a<this.length&&(delete this[a],this.b.put(a))};h.prototype.clear=function(){for(var a=0,b=this.length;a<b;a++)delete this[a];this.length=0;this.b.clear()};var aa=/([.*:;'"!@#$%^&?\-+=<>\\\/~`|(){}\[\]])/g,ba=/(\\[bcdfnrtvsw])/ig,ca=/^\/.*\/$/;function da(a){return a.replace(aa,"\\$1").replace(ba,"\\\\$1")}function m(a){return RegExp(ca.test(a)?a.substr(1,a.length-2):/\*/.test(a)?a.split("*").map(da).join("(.*?)"):da(a))};function ea(a){var b=Array.prototype.slice.call(arguments,1);return arguments[0].replace(/\{\d+\}/g,function(a){return b[a.match(/\d+/)]})}function n(){};var p=/\.swf\b/i,q=/^application\/(x-shockwave-flash|futuresplash)$/i,fa=/D27CDB6E-?AE6D-?11cf-?96B8-?444553540000/i;function r(a){var b="";if(a instanceof HTMLEmbedElement)b=a.src;else if(a instanceof HTMLObjectElement)if(a.data)b=a.data;else for(a=a.lastChild;a&&(a.nodeType!==Node.ELEMENT_NODE||"PARAM"!==a.nodeName||!(b=r(a)));a=a.previousSibling);else a instanceof HTMLParamElement&&/(?:src|movie)/i.test(a.name)&&(b=a.value);return b.trim()}
function ha(a){a=a.parentNode;return!(a instanceof HTMLObjectElement&&ia(a))}function ia(a){if(!ha(a)||fa.test(a.getAttribute("classid")))a=!1;else{var b;if(!(b=q.test(a.type)||p.test(a.data)))a:{if(a.firstChild)for(a=a.lastChild;a;a=a.previousSibling)if(a.nodeType===Node.ELEMENT_NODE&&"PARAM"===a.nodeName&&(b=a.name,"type"==b&&q.test(a.value)||("movie"==b||"src"==b)&&p.test(a.value)||"flashvars"==b)){b=!0;break a}b=!1}a=b}return a}
function s(a){return"OBJECT"===a.nodeName?ia(a):"EMBED"===a.nodeName?ha(a)?q.test(a.type)||p.test(a.src):!1:!1}var u=function(){function a(a){for(a=a.toString(16);4>a.length;)a="0"+a;return a}var b=new Uint16Array(8);window.crypto.getRandomValues(b);return a(b[0])+a(b[1])+a(b[2])+a(b[3]).substring(1)+a(b[4]).substring(1)+a(b[5])+a(b[6])+a(b[7])}();function v(){this.e=[]}v.prototype.detach=function(a){for(var b=0,c=this.e.length;b<c;b++)if(this.e[b]===a){this.e.splice(b,1);break}};
v.prototype.p=function(a){for(var b=this.e,c=0,d=b.length;c<d;c++)b[c].apply(null,arguments)};function w(){this.i={}}w.prototype.n=function(a){for(var b,c=this.i,d=arguments.length;d--;)b=arguments[d],c[b]=c[b]||new v};w.prototype.fireEvent=function(a){var b=arguments[0],c=this.i;b in c&&c[b].p.apply(c[b],Array.prototype.slice.call(arguments,1))};
w.prototype.connect=function(a,b,c){var d=this.i;if(a in d)if(!1===c)d[a]&&d[a].detach(b);else a:{a=d[a];c=0;for(d=a.e.length;c<d;c++)if(a.e[c]===b)break a;a.e.push(b)}};function x(a){if(!a||!z.l)if(a){var b=document.createElement("style");b.className="f"+u;b.appendChild(document.createTextNode('object[type$="x-shockwave-flash"]:not([classid]),object[type$="futuresplash"]:not([classid]),embed[type$="x-shockwave-flash"],embed[type$="futuresplash"]{display:none !important}'));(document.head||document.documentElement).appendChild(b);z.l=1}else{a=document.querySelectorAll("style.f"+u);for(var c=0,d=a.length;c<d;c++)(b=a.item(c))&&b.parentNode.removeChild(b);delete z.l}}
function ja(a){if(z.a){var b=m(a.pattern),c=z.a.g[a.type]||[];a.enabled?c.every(ka(b.source))&&c.push(b):c=c.filter(ka(b.source));z.a.g[a.type]=c}}
function la(a){var b=r(a),c="blocked";z.a?A("white",b)?c="whitelisted":A("black",b)?c="blacklisted":B("white",b)?c="gwhitelisted":B("black",b)&&(c="gblacklisted"):z.h&2?c="whitelisted":z.h&4&&(c="blacklisted");var d=/^((?:[a-z]+:(?:[a-z]*:)?\/\/))([^/]+)/i.exec(b);return{host:(d?d[2]:"")||document.location.host,ref:document.location.href,src:b,status:c,type:a instanceof HTMLObjectElement||a instanceof HTMLEmbedElement?a.type||"application/x-shockwave-flash":"unknown",vars:ma(a,"flashvars")||"",height:window.getComputedStyle(a,
null).height,width:window.getComputedStyle(a,null).width}}function na(){delete z.a;delete z.h;C=1}function D(a){na();a&&(z.a={},z.a.g={},a[0]&&(z.a.g.white=a[0].map(m)),a[1]&&(z.a.g.black=a[1].map(m)),z.a.j={},a[2]&&oa("white",a[2]),a[3]&&oa("black",a[3]))}function oa(a,b){var c={},d;for(d in b)c[d]={origin:m(d),patterns:b[d].map(m)};d&&(z.a.j[a]=c)}function pa(a){var b=a.src;A("black",b)||B("black",b)?a.c=4:A("white",b)||B("white",b)?a.c=2:a.c=8|C}function qa(a){a.c=z.h}
function A(a,b){return z.a&&b&&a in z.a.g?z.a.g[a].some(ra(b)):!1}function B(a,b){if(!(z.a&&b&&a in z.a.j))return!1;var c=/^((?:[a-z]+:(?:[a-z]*:)?\/\/))([^/]+)/i.exec(b),c=(c?c[1]+c[2]:"")||document.location.origin,d=z.a.j[a],e;for(e in d)if(d[e].origin.test(c))return d[e].patterns.some(ra(b));return!1}
function ma(a,b){var c="",d;if(a instanceof HTMLEmbedElement)a.hasAttribute(b)&&(c=a.getAttribute(b));else if(a instanceof HTMLObjectElement)for(var e=a.lastChild;e;e=e.previousSibling){if(e.nodeType===Node.ELEMENT_NODE&&"PARAM"===e.nodeName&&(d=ma(e,b))){c=d;break}}else a instanceof HTMLParamElement&&(c=b.toLowerCase()===a.name.toLowerCase()?a.value:"");return c}function ra(a){return function(b){return b.test(a)}}function ka(a){return function(b){return b.source!==a}}var C=1,z={};function E(a){chrome.runtime.sendMessage({type:"omni",val:a})}function sa(){G.forEach(function(a){a&&E(-1)});G=[]}var G=[];function ta(){chrome.runtime.sendMessage({type:"css"},function(a){var b=document.createElement("style");b.className="c"+u;b.appendChild(document.createTextNode(a.rules));(document.head||document.documentElement).appendChild(b)})}function H(a){ua();a&&(I.m=a.toolbaranimation,I.buttons=a.toolbar,I.click=a.clickpanel,I.o=a.panelicon,I.position=a.toolbarposition,I.k=a.paneltooltip,J=5&a.toolbar?va:wa);K.d.connect("process",xa);K.d.connect("destroy",ya)}
function ua(){J=n;L.forEach(za);L=[];I={};for(var a=document.querySelectorAll("style.c"+u),b=0,c=a.length,d;b<c;b++)(d=a.item(b))&&d.parentNode.removeChild(d);M=!1;sa()}
function xa(a){var b=a.id;if(L[b]){if(b=a.id,L[b]){var c=L[b],d,e=a,g=a.src,k=a.c,l=a.element;k&5&&(d="none",k&4&&(c instanceof HTMLDivElement&&Aa(c,l),Ba(a)));k&2&&(d="block",c instanceof HTMLDivElement&&Aa(c,l),Ba(a));k&8&&(c instanceof HTMLDivElement?d="":(c=Ca(l),I.k&&(c.title=g),!N(c)&&c.classList.add("fc-icon"),c.addEventListener("click",J,!1),O(c,"resource",a)),k&1||(c.style.setProperty("display","none"),d="block"),e=c);d&&P(l,"display",d,"!important");L[b]=e}}else c=a,d=a.src,k=a.c,l=a.element,
k&5&&(g="none"),k&2&&(g="block"),k&8&&(c=Ca(l),I.k&&(c.title=d),!N(c)&&c.classList.add("fc-icon"),k&1||(c.style.setProperty("display","none"),g="block"),c.addEventListener("click",J,!1),O(c,"resource",a)),g&&P(l,"display",g,"!important"),L[b]=c,G[a.id]||(G[a.id]=1,E(1),window.FlashControl.port&&window.FlashControl.port.postMessage({payload:[la(a.element)],origin:document.location.origin}))}function Aa(a,b){a.contains(b)&&(Da(b),a.parentNode.insertBefore(b,a),Q(a),a.classList.remove("fc-trans"))}
function wa(a){a.target===a.currentTarget&&(a.target.style.setProperty("display","none"),a=R(a.target,"resource"),a.c&4||P(a.element,"display","block","!important"))}
function va(a){a.stopPropagation();var b=a.currentTarget,c=R(b,"resource"),d=c.element;a.target===b?(I.click?(Q(b),b.style.setProperty("display","none")):Ea(b,d),c.c&4||P(d,"display","block","!important")):(a=a.target.classList,a.contains("fc-panel-button")?(Ea(b,d),c.c&4||P(d,"display","block","!important")):a.contains("fc-toolbar-button")&&a.contains("fc-toolbar-buttonunload")&&(Aa(b,d),N(b),c.c&4||P(d,"display","none","!important")))}
function Ea(a,b){if(!a.contains(b)){Q(a);if(3!==I.m){var c,d,e={width:"16px",height:"16px"};c=document.createElement("div");c.className="fc-toolbar fc-toolbar-animation-"+["fade","zoom","always","none"][I.m];if(I.buttons&1){d=document.createElement("div");d.className="fc-toolbar-button fc-toolbar-buttonunload";for(var g in e)d.style.setProperty(g,e[g]);c.appendChild(d)}e={};switch(I.position){case 3:e.right="0px";e.bottom="0px";break;case 2:e.left="0px";e.bottom="0px";break;case 1:e.top="0px";e.right=
"0px";break;default:e.top="0px",e.left="0px"}for(g in e)c.style.setProperty(g,e[g]);a.classList.add("fc-rectangle");a.insertBefore(c,a.firstChild)}a.appendChild(b);P(b,"position","static");if(b)if(b instanceof HTMLObjectElement){if(c=b.querySelectorAll("param[name=wmode]"),(c=c.length?c[c.length-1]:null)?!/(?:transparent|opaque)/.test(c.value):1)c=document.createElement("param"),c.name="wmode",c.value="opaque",b.appendChild(c),O(b,"wndmode",!0)}else/(?:transparent|opaque)/.test(b.getAttribute("wmode"))||
(b.setAttribute("wmode","opaque"),O(b,"wndmode",!0));a.classList.add("fc-trans");I.k&&a.removeAttribute("title")}}function Fa(a){var b=a;a instanceof HTMLDivElement&&(a=b,b=R(a,"resource"),a.parentNode.insertBefore(b.element,a),Q(a),N(a),a.style.setProperty("display","block"),a.classList.remove("fc-trans"));b.c&2||P(b.element,"display","none","!important")}
function Ga(a){var b=a;a instanceof HTMLDivElement&&(a=b,b=R(a,"resource"),!a.contains(b.element)&&a.style.setProperty("display","none"),Da(b.element));b.c&4||P(b.element,"display","block","!important")}
function za(a){var b=a;a instanceof HTMLDivElement&&(a=b,b=R(a,"resource"),a.contains(b.element)&&a.parentNode.insertBefore(b.element,a),R(a)&&S(a),a.parentNode.removeChild(a));Da(b.element);var c=b.element;a=c.style;var c=R(c,"css")||{},d;for(d in c)a.removeProperty(d),null!==c[d]&&a.setProperty(d,c[d]);S(b.element);delete L[b.id]}function ya(a){Ba(a);G[a.id]=0;E(-1)}
function Ba(a){var b=L[a.id];b instanceof HTMLDivElement&&(b.parentNode&&b.parentNode.removeChild(b),S(b));S(a.element);delete L[a.id]}function Q(a){a.firstChild&&(a.textContent="")}
function Ca(a){M||(M=!0,ta());var b=window.getComputedStyle(a,null),c={top:b.top,left:b.left,"float":b["float"],zIndex:b.zIndex,marginTop:b.marginTop,marginLeft:b.marginLeft,marginRight:b.marginRight,marginBottom:b.marginBottom,position:"absolute"===b.position&&"absolute"||"relative"},d=document.createElement("div");d.className="fc-panel";!I.click&&d.classList.add("fc-icon");c.width=b.width;"auto"===c.width&&a.hasAttribute("width")&&(c.width=a.width,"auto"!==c.width&&(c.width+=/[x%]$/.test(c.width)?
"":"px"));c.height=b.height;"auto"===c.height&&a.hasAttribute("height")&&(c.height=a.height,"auto"!==c.height&&(c.height+=/[x%]$/.test(c.height)?"":"px"));for(var e in c)d.style[e]=c[e];return a.nextSibling?a.parentNode.insertBefore(d,a.nextSibling):a.parentNode.appendChild(d)}
function N(a){if(!I.click)return null;var b=I.o,c=b+24;if(parseInt(a.style.width,10)<=c||parseInt(a.style.height,10)<=c)return null;b=ea("-{0}px",b/2+12);c=document.createElement("div");c.style.position="absolute";c.style.marginLeft=b;c.style.marginTop=b;c.style.left="50%";c.style.top="50%";c.className="fc-panel-button fc-panel-animation-fade fc-icon";return a.appendChild(c)}var Ha=1,T="fstore_"+Date.now(),U={};
function O(a,b,c){a=a[T]||(a[T]=Ha++);var d=U[a]||{};if("object"===typeof b)for(var e in b)"string"===typeof e&&(d[e]=b[e]);else d[b]=c;U[a]=d}function S(a,b){var c=a[T]||(a[T]=Ha++);c in U&&("undefined"!==typeof b?delete U[c][b]:delete U[c])}function R(a,b){var c=a[T];if("undefined"===typeof b)return!(!c||!U[c]);if(c&&c in U)return U[c][b]}
function P(a,b,c,d){var e=a.style,g=R(a,"css")||{};b in g||(g[b]=e.getPropertyValue(b)||null,O(a,"css",g));"undefined"!==typeof c&&(e.removeProperty(b),e.setProperty(b,c,d||null))}function Da(a){if(a&&R(a,"wndmode")){if(a instanceof HTMLObjectElement){var b=a.querySelectorAll("param[name=wmode]");(b=b.length?b[b.length-1]:null)&&b.parentNode.removeChild(b)}else a.removeAttribute("wmode");S(a,"wndmode")}}var L=[],J=n,I={},M=!1;function Ia(a){this.src=r(a);this.element=a;this.id=a[V]}
function Ja(){Ka();W=La.dispatch;X=X||new window.MutationObserver(Ma);var a={childList:!0,subtree:!0},b=document.readyState;/loaded|complete/i.test(b)?(X.disconnect(),X.observe(document,a),window.setTimeout(Y,0,document)):/loading/i.test(b)?(document.addEventListener("DOMContentLoaded",function(){document.removeEventListener("DOMContentLoaded",arguments.callee,!1);X.disconnect();X.observe(document,a);window.setTimeout(Y,0,document)},!1),X.observe(document,a)):(X.observe(document,a),window.setTimeout(Y,
0,document));Na(Z,Oa);K.d.connect(Oa,Pa)}var Z="process",Oa="destroy";function Qa(a){K.d.connect("process",a)}function Ra(){var a=W;$.forEach(function(b){a(Z,b)})}function Ka(){W=La.suppress;X&&X.disconnect();$.forEach(function(a){delete a[V]});$.clear();delete K.d}function Pa(a){a=a.element;var b=a[V];delete a[V];$.remove(b)}
function Ma(a){var b={addedNodes:[],removedNodes:[]},c=Array.prototype.push;c.apply(b.addedNodes,a[0].addedNodes);c.apply(b.removedNodes,a[0].removedNodes);for(var c=1,d=a.length;c<d;c++){for(var e=b,g=a[c],k=void 0,l=void 0,y=g.addedNodes,F=e.removedNodes,t=0,ga=y.length;t<ga;t++)-1!=(l=F.indexOf(y[t]))&&F.splice(l,1);y=g.removedNodes;F=e.addedNodes;k=e.removedNodes;t=0;for(ga=y.length;t<ga;t++)-1!=(l=F.indexOf(y[t]))?F.splice(l,1):k.push(y[t]);Array.prototype.push.apply(e.addedNodes,g.addedNodes)}b.removedNodes.forEach(Sa);
b.addedNodes.forEach(Ta)}function Ua(a,b){var c=(a||document).querySelectorAll(Va);if(b){for(var d=[],e=0,g=c.length;e<g;e++)s(c[e])&&d.push(c[e]);c=d}return c}var La={dispatch:function(a,b){var c=a||Z;if(!b.hasOwnProperty(V)){var d=V,e;e=$;if(isNaN(e.b.b.length?e.b.b[e.b.f]:void 0))e=e.push(b)-1;else{var g=e.b.get();e[g]=b;e=g}b[d]=e}K.d.fireEvent(c,new Ia(b))},monitor:function(){},suppress:function(){}},W;
function Sa(a){a.nodeType===Node.ELEMENT_NODE&&(s(a)?(delete $[a[V]],W(Oa,a)):(a=Ua(a),Array.prototype.forEach.call(a,Sa)))}function Ta(a){a.nodeType===Node.ELEMENT_NODE&&(s(a)?W(Z,a):Y(a))}function Y(a){var b=W;a=Ua(a,!0);for(var c=0;c<a.length;c++)b(Z,a[c])}var X=null,Va="object,embed",V="fcte_"+Date.now(),$=new h;function Na(a){delete K.d;K.d=new w;for(var b=0;b<arguments.length;b++)K.d.n(arguments[b])}var K={};function Wa(){chrome.runtime.sendMessage({type:"status"},function(a){window.FlashControl(a.status,a)})}
window.navigator.plugins["Shockwave Flash"]&&document.documentElement instanceof HTMLHtmlElement?(window.FlashControl=function(){var a=Array.prototype.slice.apply(arguments);switch(a[0]){case "capture":Ja();var b=a[1].flags;D(a[1].filterset);C=0|b&1;Qa(pa);H(a[1].preferences);break;case "allow":Ja();D();z.h=2;Qa(qa);H();window.setTimeout(x,0,!1);break;case "deny":Ja();D();z.h=4;Qa(qa);H();window.setTimeout(x,0,!0);break;case "destroy":Ka();na();ua();window.setTimeout(x,0,!1);break;case "block":C=
0|a[1]&1;L.forEach(a[1]?Fa:Ga);window.setTimeout(x,0,a[1]);break;case "filter":a[2]?window.FlashControl(a[1]):("allow"===a[1]&&x(!0),Wa());break;case "invalidate":Array.isArray(a[1])&&(a[1].forEach(ja),Ra());break;case "revalidate":Wa();break;case "enable":window.FlashControl("filter","allow",!a[1]),a[1]||window.FlashControl("destroy")}},window.setTimeout(x,0,!0),Wa(),chrome.runtime.onConnect.addListener(function(a){window.FlashControl.port=a;a.onMessage.addListener(function(b){switch(b.cmd){case "filter":window.FlashControl("invalidate",
b.data);break;case "resources":a.postMessage({payload:Ua(document,!0).map(la),origin:document.location.origin})}});a.onDisconnect.addListener(function(){delete window.FlashControl.port})})):window.FlashControl=n;
