#!/bin/bash -e
# regenerate rails secret key and mysql password

. /etc/default/inithooks

APPNAME=$(cat /etc/hostname)
[ "$APPNAME" == "rails" ] && APPNAME=railsapp ## namespace conflict
WEBROOT=/var/www/$APPNAME

# rails 3.2
CONF=$WEBROOT/config/initializers/secret_token.rb
[ -e $CONF ] && sed -i "s|Application.config.secret_token =.*|Application.config.secret_token = '$(mcookie)$(mcookie)$(mcookie)$(mcookie)'|" $CONF

# rails 2.3
CONF=$WEBROOT/config/initializers/session_store.rb
[ -e $CONF ] && sed -i "s|:secret      => .*|:secret      => \'$(mcookie)$(mcookie)\'|" $CONF

# rails 2.2
CONF=$WEBROOT/config/site.yml
[ -e $CONF ] && sed -i "s|^salt: .*|salt: \"$(mcookie)\"|" $CONF

# regen mysql password
PASSWORD=$(mcookie)
CONF=$WEBROOT/config/database.yml
sed -i "s|password:.*|password: $PASSWORD|g" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=$APPNAME --pass="$PASSWORD"

# remove innodb logfiles (workarounds really weird bug)
rm -f /var/lib/mysql/ib_logfile*

# restart passenger
touch $WEBROOT/tmp/restart.txt

