#!/bin/bash -e
# regenerate rails secret key and mysql password

. /etc/default/inithooks

# rails 2.3
CONF=/var/www/railsapp/config/initializers/session_store.rb
[ -e $CONF ] && sed -i "s|:secret      => \(.*\)|:secret      => \'$(mcookie)$(mcookie)\'|" $CONF

# rails 2.2
CONF=/var/www/railsapp/config/site.yml
[ -e $CONF ] && sed -i "s|^salt: \(.*\)|salt: \"$(mcookie)\"|" $CONF

# regen mysql password
PASSWORD=$(mcookie)
CONF=/var/www/railsapp/config/database.yml
sed -i "s|^  password: \(.*\)|  password: $PASSWORD|g" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=railsapp_user --pass="$PASSWORD"

# remove innodb logfiles (workarounds really weird bug)
rm -f /var/lib/mysql/ib_logfile*

# restart passenger
touch /var/www/railsapp/tmp/restart.txt

