#Apache configuration

<VirtualHost *:12322>
    SSLEngine on
    ServerAdmin webmaster@localhost
    DocumentRoot /usr/share/adminer/adminer
    Alias /adminer/static /usr/share/adminer/adminer/static
    Alias /externals /usr/share/adminer/externals
    Alias /editor   /usr/share/adminer/editor
</VirtualHost>

<Directory /usr/share/adminer/adminer>
    Options FollowSymLinks
    DirectoryIndex tkl-index.php

    <IfModule mod_php.c>
        AddType application/x-httpd-php .php
    </IfModule>
</Directory>

<Directory /usr/share/adminer/editor>
    Options FollowSymLinks
    DirectoryIndex index.php

    <IfModule mod_php.c>
        AddType application/x-httpd-php .php
    </IfModule>
</Directory>

<Directory /usr/share/adminer/externals>
    # Follow symlink to 'jush' (libjs-jush & libjs-jquery-jush)
    Options +FollowSymLinks
</Directory>
