# LigHTTPd Adminer config

# Alias the directories needed since we are using adminer in doc root, use a
# variable so we don't need to state them twice
var.alias_redirects = (
    "/adminer/"         => "/usr/share/adminer/adminer/",
    "/adminer-editor/"  => "/usr/share/adminer/editor/",
    "/externals/"       => "/usr/share/adminer/externals/"
)

# Map tkl-index.php URL to the actual file in /etc/adminer/
$HTTP["url"] == "/tkl-index.php" {
    fastcgi.server = (
        ".php" => ((
            "socket" => "/run/php/php-fpm.sock", # may need adjustment?
            "check-local" => "disable",
            "bin-environment" => (
                "SCRIPT_FILENAME" => "/etc/adminer/tkl-index.php"
            )
        ))
    )
}

index-file.names += ( "tkl-index.php" )

# IPv4
$SERVER["socket"] == "0.0.0.0:12322" {
    ssl.engine = "enable"
    server.document-root = "/usr/share/adminer/adminer/"
    alias.url = alias_redirects
    follow-symlink = "enable"
}

# IPv6
$SERVER["socket"] == "[::]:12322" {
    ssl.engine = "enable"
    server.document-root = "/usr/share/adminer/adminer/"
    alias.url = alias_redirects
    follow-symlink = "enable"
}
