# LigHTTPd Adminer config

# Alias the directories needed since we are using adminer in doc root, use a
# variable so we don't need to state them twice
var.alias_redirects = (
    "/adminer/"         => "/usr/share/adminer/adminer/",
    "/adminer-editor/"  => "/usr/share/adminer/editor/",
    "/externals/"       => "/usr/share/adminer/externals/"
)

# IPv4
$SERVER["socket"] == "0.0.0.0:12322" {
    ssl.engine = "enable"
    server.document-root = "/usr/share/adminer/adminer/"
    index-file.names = ( "tkl-index.php", "index.php" )
    alias.url = alias_redirects
    follow-symlink = "enable"

    accesslog.filename = "/var/log/adminer/access.log"
    server.errorlog = "/var/log/adminer/error.log"
}

# IPv6
$SERVER["socket"] == "[::]:12322" {
    ssl.engine = "enable"
    server.document-root = "/usr/share/adminer/adminer/"
    index-file.names = ( "tkl-index.php", "index.php" )
    alias.url = alias_redirects
    follow-symlink = "enable"

    accesslog.filename = "/var/log/adminer/access.log"
    server.errorlog = "/var/log/adminer/error.log"
}
