# Nginx Adminer Config

server {
    listen 12322 ssl;
    listen [::]:12322 ssl;
    include /etc/nginx/snippets/ssl.conf;
    root /usr/share/adminer/adminer/;

    access_log /var/log/adminer/access.log;
    error_log /var/log/adminer/error.log;

    location / {
        index tkl-index.php index.php;
        try_files $uri $uri/ /tkl-index.php?$args;
    }

    # Route tkl-index.php to /etc/adminer/
    location = /tkl-index.php {
        fastcgi_param HTTPS on;
        fastcgi_param SCRIPT_FILENAME /etc/adminer/tkl-index.php;
        include /etc/nginx/snippets/php-fpm.conf;
    }

    location ~ \.php$ {
        fastcgi_param HTTPS on;
        include /etc/nginx/snippets/php-fpm.conf;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /adminer {
        alias /usr/share/adminer/adminer/;
    }

    location /adminer-editor {  
        alias /usr/share/adminer/editor/;
    }

    location /externals {  
        alias /usr/share/adminer/externals/;
        disable_symlinks off;
    }
}
